# Generated by Django 3.1.7 on 2021-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oldprice', models.TextField()),
                ('newprice', models.TextField()),
                ('img', models.ImageField(upload_to='img/png')),
            ],
        ),
    ]
