# Generated by Django 3.1.7 on 2021-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typescode',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
