# Generated by Django 3.1.7 on 2021-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typescode_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typescode',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
